### PR TITLE
Cherry pick of changelogs from 1.6.1 to master

### PR DESCRIPTION
**Pull request by swathinsankaran**
Changlog updates for release1.6.1

### CODE REVIEW

**Comment by swathinsankaran** [comment]
build amko

**Comment by swathinsankaran** [comment]
build amko

**Review by RiyaGaniga-avi — APPROVED** [review]

**Comment by RiyaGaniga-avi** [comment]
build amko

**Comment by swathinsankaran** [comment]
I have added these changes to my other PR. Hence closing this.

**Pull request closed without merging**
