### PR TITLE
AV-175601 include priority in checksum calculation for gslbhostrule

### PR DESCRIPTION
**Pull request by arihantg**

### CODE REVIEW

**Comment by arihantg** [comment]
build amko

**Comment by arihantg** [comment]
build amko

**Review by swathinsankaran — DISMISSED** [review]
LGTM. Could you please attach the results of GSLBhostrule FTs?

**Comment by arihantg** [comment]
build amko

**Comment by swathinsankaran** [comment]
build amko

**Comment by arihantg** [comment]
image

**Comment by swathinsankaran** [comment]
build amko

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Comment by swathinsankaran** [comment]
build amko

**Pull request merged**
