### PR TITLE
AV-168336 : SRP data submission for AMKO

### PR DESCRIPTION
**Pull request by DixitAakash**
This PR is for adding a script to AMKO repository, for getting the path where a specific build is stored in the build server. The script will take build number and branch name as parameters for computing the path. This script will be used by a Jenkins job, created for getting and submitting the SRP provenance data based on build number and branch.

### CODE REVIEW

**Comment by DixitAakash** [comment]
build amko

**Comment by DixitAakash** [comment]
build amko

**Comment by swathinsankaran** [comment]
build amko

**Comment by swathinsankaran** [comment]
build amko

**Comment by swathinsankaran** [comment]
build amko

**Review by swathinsankaran — APPROVED** [review]
LGTM

**Review by akshayhavile — APPROVED** [review]

**Pull request merged**
